name: We /r/predictable
markdown: redcarpet
pygments: true
subreddits:
  - pics
  - funny
  - gaming
  - AskReddit
  - worldnews
  - news
  - videos
  - IAmA
  - todayilearned
  - aww
  - AdviceAnimals
  - science
  - Music
  - movies
  - bestof
  - books
  - EarthPorn
  - explainlikeimfive
  - gifs
  - television
  - askscience
  - sports
  - mildlyinteresting
  - LifeProTips
  - woahdude
  - Unexpected
  - reactiongifs
  - Showerthoughts
  - food
  - Jokes
  - photoshopbattles
  - firstworldanarchists
  - FoodPorn
  - HistoryPorn
  - WTF
  - leagueoflegends
  - gameofthrones
  - 4chan
  - nba
  - dogecoin
  - circlejerk
  - politics
  - DotA2
  - TrollXChromosomes
  - technology
  - soccer
  - MakeupAddiction
  - gentlemanboners
  - pokemon
  - atheism
  - cats
  - Games
  - hockey
  - Minecraft
  - tumblr
  - fffffffuuuuuuuuuuuu
